### PR TITLE
removed GA key and added in env variable

### PR DESCRIPTION
**Pull request by ZachLamb**
**Pull request recommendations:**
- [x] Link to any relevant issue in the PR description. 
- [x] Provide context of changes. ( added in Google Analytics env)
- [x] Provide relevant tests for your feature or bug fix (if applicable).
- [x] Provide or update documentation for any feature added by your pull request (if applicable).
- [x] Provide a link to a staging deployment or screenshots of changes (if applicable).

Thanks for contributing!

### CODE REVIEW

**Review by sscchan — APPROVED** [review]

**Comment by ptressel** [comment]
Was that a private key?  And was it an actual key rather than a fake one?  If so, you should be aware that you have not removed it from the repo.  It is still in there.  This is a case where rewriting history is the right thing to do.  Or change your GA keys.

**Comment by ZachLamb** [comment]
@ptressel , thanks for double-checking me on this! I changed the GA key before pushing up and merging this change.

**Comment by ptressel** [comment]
@ZachLamb  Yay!!  (FYA:  Last year I had to do a massive history rewrite when I discovered that people had been committing entire 3rd party libraries with wildly incompatible licenses to our MIT-licenced repo.  Plus large media files like videos.  Many thanks to the authors of git filter-branch...)

**Comment by ZachLamb** [comment]
@ptressel , oh man! That sounds rough! I will keep filter-branch in mind the future! I haven't been in that situation....yet! Looking forward to working with you on this project in the future! :)

**Pull request merged**
